#!/usr/bin/env bash
#script that configures a server to listen to 80 port
#remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
#configures Nginx to listen to port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart Nginx
service nginx restart
