#!/usr/bin/env bash
#  Bash script that gives you information about the holbertonschool file.

ALX="school"

if [ -e "$ALX" ]
then
    echo "school file exists"
    if [ ! -s "$ALX" ]
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$ALX" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
